//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_PR16
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public double Cost { get; set; }
        public string Status { get; set; }
        public Nullable<int> ID_Delivery { get; set; }
        public int ID_Client { get; set; }
        public int ID_Product { get; set; }
        public int ID_TypeOfPayment { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
        public virtual TypeOfPayment TypeOfPayment { get; set; }
    }
}
